DROP TABLE IF EXISTS task;

CREATE TABLE task (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    completed   BOOLEAN      NOT NULL DEFAULT FALSE
);

-- ---------- RAG 知识库 ----------

DROP TABLE IF EXISTS knowledge_chunk;
DROP TABLE IF EXISTS knowledge_document;

CREATE TABLE knowledge_document (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(255) NOT NULL,
    file_name   VARCHAR(255),
    content     CLOB,
    chunk_count INT          NOT NULL DEFAULT 0,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE knowledge_chunk (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT       NOT NULL REFERENCES knowledge_document(id),
    seq         INT          NOT NULL,
    content     VARCHAR(8000) NOT NULL,
    embedding   CLOB,             -- JSON float 数组；为 NULL 表示未成功向量化
    dim         INT
);

CREATE INDEX idx_knowledge_chunk_doc ON knowledge_chunk(document_id, seq);
