-- 幂等建表：文件模式下每次启动都会执行，绝不能用 DROP；
-- 已存在的表/索引原样保留，数据跨重启持久化。

CREATE TABLE IF NOT EXISTS task (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    completed   BOOLEAN      NOT NULL DEFAULT FALSE
);

-- ---------- RAG 知识库 ----------

CREATE TABLE IF NOT EXISTS knowledge_document (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(255) NOT NULL,
    file_name   VARCHAR(255),
    content     CLOB,
    chunk_count INT          NOT NULL DEFAULT 0,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS knowledge_chunk (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT       NOT NULL REFERENCES knowledge_document(id),
    seq         INT          NOT NULL,
    content     VARCHAR(8000) NOT NULL,
    embedding   CLOB,             -- JSON float 数组；为 NULL 表示未成功向量化
    dim         INT
);

CREATE INDEX IF NOT EXISTS idx_knowledge_chunk_doc ON knowledge_chunk(document_id, seq);
